config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'visitors#index'
  namespace :account do
    resources :users
  end
  resources :clients
  resources :file_matters do
  	get :autocomplete_client_name, :on => :collection
	end
  resources :lawyers
  resources :carl_entries
end

app/models/carl_entry.rb
class CarlEntry < ActiveRecord::Base
	belongs_to :category
	has_many :carl_fields, dependent: :destroy
	accepts_nested_attributes_for :carl_fields
end

app/controllers/carl_entries_controller.rb
class CarlEntriesController < ApplicationController


	before_filter :set_carl_entry, only: [:show, :update, :destroy]

  def index
    @carl_entries = CarlEntry.paginate(:page => params[:page], :per_page => 20)
    # render json: @carl_entries
  end

  def new
    @carl_entry = CarlEntry.new
    @clients = Client.all
  end
  
  def edit
    @carl_entry = CarlEntry.find(params[:id])
  end

  def show
    @carl_entry = CarlEntry.find(params[:id])
    @carl_fields = CarlField.where(carl_entry_id: @carl_entry.id)
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf         => "Reimbursement Form",
              :orientation  => 'Portrait',
              :page_width   => '13in',
              :margin => {:top       => 1,
                           :bottom   => 1}
      end
    end
  end

  def create
    @carl_entry = CarlEntry.new(carl_entry_params)

    if @carl_entry.save
      flash[:success] = 'Case Reference was successfully created.'
      redirect_to carl_entries_path
    else
      flash[:error] = 'An error occured while creating new carl_entry.'
      render 'new'
    end
  end

  def update
    if @carl_entry.update(carl_entry_params)
      flash[:success] = 'Case Reference was successfully updated.'
      redirect_to carl_entries_path
    else
      flash[:error] = 'An error occured while creating new carl_entry.'
      render 'new'
    end
  end
  
  def destroy
    @carl_entry.destroy!
    flash[:success] = 'Case Reference has been deleted.' 
    redirect_to carl_entries_path
  end

  private

    def set_carl_entry
      @carl_entry = CarlEntry.find(params[:id])
    end
      
    def carl_entry_params
      params.require(:carl_entry).permit(:entry_date, :category_id, :user_id, :assigned_person, :file_matter_id, 
        :case_reference_number, :client_id, :client_name, :tin_of_client, :address, :bus_name_style, :terms_of_payment, 
        :osc_pwd_id_no, :prepared_by,
        :approved_by, carl_fields_attributes: [:entry_date, :check_num, :particular, :amount, :carl_entry_id] )
    end
end

app/views/carl_entries/_carl_field_fields.html.slim
tr.nested-fields
	td= f.text_field :entry_date, class: 'form-control datepicker2'
	td= f.text_field :check_num, class: 'form-control'
	td= f.text_field :particular, class: 'form-control'
	td= f.text_field :amount, class: 'form-control'
	td= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger btn-mini"
javascript:
  $(document).ready(function(){
    $('.datepicker2').datepicker();
  });

app/views/carl_entries/_form.html.slim
= form_for @carl_entry, html: { class: '' } do |f|
  .col-md-4.signin-form
    .form-group
      = f.label :client_name, 'Client Name'
      = f.text_field :client_name, class: 'form-control '
    .form-group
      = f.label :address, "Address"
      = f.text_area :address, class: 'form-control', rows: 5, style:"resize: none;"
  .col-md-4.signin-form
    .form-group
      = f.label :bus_name_style, 'Bus Name/Style'
      = f.text_field :bus_name_style, class: 'form-control '
    .form-group
      = f.label :terms_of_payment, 'Terms of Payment'
      = f.text_field :terms_of_payment, class: 'form-control '
    .form-group
      = f.label :osc_pwd_id_no, 'OSCA/PWD Id No.'
      = f.text_field :osc_pwd_id_no, class: 'form-control '
  .col-md-4.signin-form
    .form-group
      = f.label 'Category'
      = f.select :category_id, Category.all.map{ |e| [e.name, e.id] }, {include_blank: true }, class: 'form-control '
    .form-group
      = f.label :tin_of_client, 'TIN Of CLient'
      = f.text_field :tin_of_client, class: 'form-control '
    .form-group
      = f.label :entry_date, 'Date'
      = f.text_field :entry_date, class: 'form-control datepicker'
    
  .col-md-10.signin-form
    = link_to_add_association "<i class='fa fa-plus'></i> Add Entry".html_safe, f, :carl_fields, class: 'btn btn-success', 'data-association-insertion-method' => 'append', 'data-association-insertion-node' => '#team-members-body'
  .col-md-12.signin-form
    br  
    table.table.table-bordered.table-hover
      thead
        tr
          th width="10%" Entry Date
          th width="10%" Check #
          th width="60%" Particulars
          th width="10%" Amount
          th width="10%" Action
      tbody id="team-members-body"
        = f.fields_for :carl_fields do |cf|
          = render 'carl_field_fields', :f => cf
  .col-md-12.signin-form
    div
      = f.submit "Save", class: 'pull-right btn btn-primary btn'

javascript:
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });
/ css:
/   .container{
/     min-height: 100%;
/   }
/   .show_off{
/     display:none;
/   }

app/views/carl_entries/edit.html.slim
.panel.panel-info
  .panel-heading
    h3.panel-title Edit Entry
  .panel-body
		.col-sm-12
			.row
				= render 'form'

app/views/carl_entries/index.html.slim
.panel.panel-yellow
  .panel-heading
    h3.panel-title Cash Advance, Reimbursement and Loan List
  .panel-body
    .col-md-12
      br
      .col-sm-12.title-header
        = link_to 'Create New Entry', new_carl_entry_path, class: 'btn btn-warning pull-right'
      br
      br
      br
      .col-sm-12
        .row
          table.table.table-hovered
            thead
              tr.warning
                th Entry Date
                th Transaction Type
                th Assigned User
                th File Reference No.
                th Client
                th Action
            tbody
            - @carl_entries.each do |carl_entry|
              tr
                td= carl_entry.entry_date
                td= carl_entry.category_id.nil? ? '' : carl_entry.category.name
                td= carl_entry.assigned_person
                td= carl_entry.case_reference_number
                td= carl_entry.client_name
                td 
                  = link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_carl_entry_path(carl_entry), class: 'btn btn-xs btn-warning',"data-toggle"=> "tooltip", "data-placement" => "top", "title" => "Edit"
                  '&nbsp
                  = link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, carl_entry_path(carl_entry), method: :delete, 'data-confirm' => 'Are you sure you want to delete this carl_entr?', class: 'btn btn-xs btn-danger'," data-toggle"=> "tooltip", "data-placement" => "top", "title" => "Delete"
                  '&nbsp
                  = link_to "<i class='glyphicon glyphicon-file'></i>".html_safe, carl_entry_path(carl_entry), class: 'btn btn-xs btn-info'," data-toggle"=> "tooltip", "data-placement" => "top", "title" => "Delete"

app/views/carl_entries/new.html.slim
.panel.panel-warning
  .panel-heading
    h3.panel-title Create Entry
  .panel-body
		.col-sm-12
			.row
				= render 'form'

app/views/carl_entries/show.html.slim
.panel.panel-warning
  .panel-heading
    h3.panel-title Show Entry
  .panel-body
  	.col-sm-12
			= link_to "Print to PDF".html_safe, carl_entry_path(:id => params[:id], :format => 'pdf'), class: 'btn btn-small btn-primary pull-right', id:"generate-report", target: "_blank"
  	.col-sm-12
  		br
  	.col-sm-12
  	  table.table.table-bordered
  	  	tr
  	  		td.bold Client Name
  	  		td = @carl_entry.client_name
  	  		td.bold Bus Name/Style
  	  		td = @carl_entry.bus_name_style
  	  	tr
  	  		td.bold Terms of Payment
  	  		td = @carl_entry.terms_of_payment
  	  		td.bold OSCA/PWD Id No.
  	  		td = @carl_entry.osc_pwd_id_no
  	  	tr
  	  		td.bold Category
  	  		td = @carl_entry.category.name
  	  		td.bold TIN Of CLient
  	  		td = @carl_entry.tin_of_client
  	  	tr
  	  		td.bold Address
  	  		td = @carl_entry.address
  	  		td.bold Date
  	  		td = @carl_entry.entry_date
  	  
  	  table.table.table-bordered
  	  	thead
  	  		th width="10%" Entry Date
  	  		th width="10%" Check #
  	  		th width="60%" Particulars
  	  		th width="10%" Amount
        tbody
          - @total_amount = []
          - @carl_fields.each do |cf|
          	tr
          		td= cf.entry_date
          		td= cf.check_num
          		td= cf.particular
          		td= number_to_currency(cf.amount, :unit => "")
          		- @total_amount << cf.amount
        tfoot	
        	tr
        	  td colspan="3"
        	  td = number_to_currency(@total_amount.inject(:+).to_f, :unit => "Php ")

app/views/carl_entries/show.pdf.slim
= wicked_pdf_stylesheet_link_tag "application"
br
br
.col-sm-12
  table.table.table-bordered
    tr
      td.bold Client Name
      td = @carl_entry.client_name
      td.bold Bus Name/Style
      td = @carl_entry.bus_name_style
    tr
      td.bold Terms of Payment
      td = @carl_entry.terms_of_payment
      td.bold OSCA/PWD Id No.
      td = @carl_entry.osc_pwd_id_no
    tr
      td.bold Category
      td = @carl_entry.category.name
      td.bold TIN Of CLient
      td = @carl_entry.tin_of_client
    tr
      td.bold Address
      td = @carl_entry.address
      td.bold Date
      td = @carl_entry.entry_date
  
  table.table.table-bordered
    thead
      th width="10%" Entry Date
      th width="10%" Check #
      th width="60%" Particulars
      th width="10%" Amount
    tbody
      - @total_amount = []
      - @carl_fields.each do |cf|
        tr
          td= cf.entry_date
          td= cf.check_num
          td= cf.particular
          td= number_to_currency(cf.amount, :unit => "")
          - @total_amount << cf.amount
    tfoot 
      tr
        td colspan="3"
        td = number_to_currency(@total_amount.inject(:+).to_f, :unit => "Php ")
css:      
  .form-group > .col-md-3{
    text-align: right;
  }	
  td{
    font-size: 10px;
  }
  .sm_font {
    font-size: 9px;
  }
  / .borderless tbody tr td, .borderless thead tr th {
  /   border: none;
  / }
  .vcenter td {
    vertical-align: middle!important;
  }
      