config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'visitors#index'
  namespace :account do
    resources :users
  end
  resources :clients
  resources :file_matters do
  	get :autocomplete_client_name, :on => :collection
	end
  resources :lawyers
  resources :carl_entries
end

app/models/client.rb
class Client < ActiveRecord::Base
	belongs_to :file_matter

	validates :email, presence: true, format: /@/
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_filter :set_client, only: [:show, :update, :destroy]

  def index
    @q = Client.ransack(params[:q])
    @clients = @q.result.paginate(:page => params[:page], :per_page => 20)
    # render json: @clients
  end

  def new
    @client = Client.new
  end
  
  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      flash[:success] = 'Client was successfully created.'
      redirect_to clients_path
    else
      flash[:error] = 'An error occured while creating new client.'
      render 'new'
    end
  end

  def update
    if @client.update(client_params)
      flash[:success] = 'Client was successfully updated.'
      redirect_to clients_path
    else
      flash[:error] = 'An error occured while creating new client.'
      render 'new'
    end
  end
  
  def destroy
    @client.destroy!
    flash[:success] = 'Client has been deleted.' 
    redirect_to clients_path
  end

  private

    def set_client
      @client = Client.find(params[:id])
    end
      
    def client_params
      params.require(:client).permit(:name, :email, :address, :contact_number, :position, :contact_person)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.slim
= form_for @client, html: { class: '' } do |f|
  .col-md-5.signin-form
    .form-group
      = f.label :name, 'Client Name'
      = f.text_field :name, class: 'form-control '
    .form-group
      = f.label :contact_number, 'Contact Number'
      = f.text_field :contact_number, class: 'form-control '
    .form-group
      = f.label :address, "Address"
      = f.text_area :address, class: 'form-control', rows: 5, style:"resize: none;"
  .col-md-5.signin-form
    .form-group
      = f.label :contact_person, 'Contact Person'
      = f.text_field :contact_person, class: 'form-control '
    .form-group
      = f.label :email
      = f.email_field :email, :autofocus => true, class: 'form-control validate[custom[email]]'
    .form-group
      = f.label :position, 'Designation'
      = f.text_field :position, class: 'form-control '
    
  .col-md-10.signin-form
    div
      = f.submit "Save", class: 'pull-right btn btn-primary btn'
css:
  .container{
    min-height: 100%;
  }
  .show_off{
    display:none;
  }

/ dropdown_values, {include_blank: true, selected: @item.source_of_funds_id},

app/views/clients/edit.html.slim
.panel.panel-info
  .panel-heading
    h3.panel-title Edit Entry
  .panel-body
		.col-sm-12
			.row
				= render 'form'

app/views/clients/index.html.slim
.panel.panel-yellow
  .panel-heading
    h3.panel-title Client List
  .panel-body
    .col-md-12
      br
      .col-sm-12.title-header
        = link_to 'Create Client', new_client_path, class: 'btn btn-warning pull-right'
      br
      br
      br
      .col-sm-12
        .row
        = search_form_for @q do |f|
          table.table.table-hovered
            thead
              tr.warning
                th.graycolor = sort_link(@q, :name, 'Client Name', default: :desc)
                th Action
              tr
                td = f.search_field :name_cont, class: 'form-control'
                td
                  input.btn.btn-primary type="submit" value="Search" icon="ok"
            tbody
            - @clients.each do |client|
              tr
                td= client.name
                td 
                  = link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_client_path(client), class: 'btn btn-xs btn-warning',"data-toggle"=> "tooltip", "data-placement" => "top", "title" => "Edit"
                  '&nbsp
                  = link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, client_path(client), method: :delete, 'data-confirm' => 'Are you sure you want to delete this client?', class: 'btn btn-xs btn-danger'," data-toggle"=> "tooltip", "data-placement" => "top", "title" => "Delete"
          div.pull-right.apple_pagination.col-sm-12
            = will_paginate @users

app/views/clients/new.html.slim
.panel.panel-warning
  .panel-heading
    h3.panel-title Create Client
  .panel-body
		.col-sm-12
			.row
				= render 'form'