config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'visitors#index'
  namespace :account do
    resources :users
  end
  resources :clients
  resources :file_matters do
  	get :autocomplete_client_name, :on => :collection
	end
  resources :lawyers
  resources :carl_entries
end

app/models/file_matter.rb
class FileMatter < ActiveRecord::Base
	has_many :clients
	has_many :assigned_lawyers, :dependent => :destroy
  accepts_nested_attributes_for :assigned_lawyers, :allow_destroy => true
end

app/controllers/file_matters_controller.rb
class FileMattersController < ApplicationController
  autocomplete :client, :name
	before_filter :set_file_matter, only: [:show, :update, :destroy]

  def index
    @q = FileMatter.ransack(params[:q])
    @file_matters = @q.result.paginate(:page => params[:page], :per_page => 20)
    # render json: @file_matters
  end

  def new
    @file_matter = FileMatter.new
    @clients = Client.all
    @file_matter.assigned_lawyers.build
  end
  
  def edit
    @file_matter = FileMatter.find(params[:id])
  end

  def create
    @file_matter = FileMatter.new(file_matter_params)

    if @file_matter.save
      flash[:success] = 'Case Reference was successfully created.'
      redirect_to file_matters_path
    else
      flash[:error] = 'An error occured while creating new file_matter.'
      render 'new'
    end
  end

  def update
    if @file_matter.update(file_matter_params)
      flash[:success] = 'Case Reference was successfully updated.'
      redirect_to file_matters_path
    else
      flash[:error] = 'An error occured while creating new file_matter.'
      render 'new'
    end
  end
  
  def destroy
    @file_matter.destroy!
    flash[:success] = 'Case Reference has been deleted.' 
    redirect_to file_matters_path
  end

  private

    def set_file_matter
      @file_matter = FileMatter.find(params[:id])
    end
      
    def file_matter_params
      params.require(:file_matter).permit(:year, :file_code, :volume, :client_id, :title, :case_number, :case_date, :amount, :currency_used,
        assigned_lawyers_attributes: [:file_matter_id, :client_id, :lawyer_id, :amount, :file_matter_pricing] )
    end

end

app/views/file_matters/_assigned_lawyer_fields.html.slim
tr.nested-fields
	td= f.select :lawyer_id, Lawyer.all.map{ |e| [e.full_name, e.id] }, {include_blank: true }, class: 'form-control '
	td= f.text_field :amount, class: 'form-control'
	td= f.text_field :file_matter_pricing, class: 'form-control'
	td= link_to_remove_association "<i class='glyphicon glyphicon-trash'></i>".html_safe, f, class: "btn btn-danger btn-mini"

app/views/file_matters/_form.html.slim
= form_for @file_matter, html: { class: '' } do |f|
  .col-md-5.signin-form
    .form-group
      = f.label :year, 'Year'
      = f.text_field :year, class: 'form-control '
    .form-group
      = f.label :file_code, 'File Reference No.'
      = f.text_field :file_code, class: 'form-control '
    .form-group
      = f.label :title, "Case Title"
      = f.text_area :title, class: 'form-control', rows: 5, style:"resize: none;"
  .col-md-5.signin-form
    .form-group
      = f.label 'Client'
      / = f.select :client_id, Client.all.map{ |e| [e.name, e.id] }, {include_blank: true }, class: 'form-control '
      = f.autocomplete_field :client_id, autocomplete_client_name_file_matters_path, class: 'form-control'
    .form-group
      = f.label :case_date, 'Date Open'
      = f.text_field :case_date, class: 'form-control '
    .form-group
      = f.label :case_number, 'Case No.'
      = f.text_field :case_number, class: 'form-control '
    .form-group
      = f.label :currency_used, 'Currency'
      = f.text_field :currency_used, class: 'form-control '
  .col-md-10.signin-form
    .form-group
      = link_to_add_association "<i class='fa fa-plus'></i>Add Lawyer".html_safe, f, :assigned_lawyers, class: 'btn btn-success', 'data-association-insertion-method' => 'append', 'data-association-insertion-node' => '#team-members-body'
  .col-md-12.signin-form
    br  
    table.table.table-bordered.table-hover
      thead
        tr
          th width="40%" Lawyer Name
          th width="20%" Rate
          th width="20%" Rate per Case
          th width="20%" Action
      tbody id="team-members-body"
        = f.fields_for :assigned_lawyers do |cf|
          = render 'assigned_lawyer_fields', :f => cf
  .col-md-10.signin-form
    div
      = f.submit "Save", class: 'pull-right btn btn-primary btn'
css:
  .container{
    min-height: 100%;
  }
  .show_off{
    display:none;
  }

/ dropdown_values, {include_blank: true, selected: @item.source_of_funds_id},

app/views/file_matters/edit.slim
.panel.panel-info
  .panel-heading
    h3.panel-title Edit Case Reference
  .panel-body
    .col-sm-12
      .row
        = render 'form'

app/views/file_matters/index.html.slim
.panel.panel-yellow
  .panel-heading
    h3.panel-title Case File Reference List
  .panel-body
    .col-md-12
      br
      .col-sm-12.title-header
        = link_to 'Create Case File Reference', new_file_matter_path, class: 'btn btn-warning pull-right'
      br
      br
      br
      .col-sm-12
        
        .row
          = search_form_for @q do |f|
            table.table.table-hovered
              thead
                tr.warning
                  th.graycolor width='20%' = sort_link(@q, :file_code, 'File Code', default: :desc)
                  th.graycolor width='30%' = sort_link(@q, :title, 'Case Title', default: :desc)
                  th.graycolor width='30%' = sort_link(@q, :case_number, 'Case No.', default: :desc)
                  th width='10%' Action
                tr
                  td = f.search_field :file_code_cont, class: 'form-control'
                  td = f.search_field :title_cont, class: 'form-control'
                  td = f.search_field :case_number_cont, class: 'form-control'
                  td
                    input.btn.btn-primary type="submit" value="Search" icon="ok"
              tbody
              - @file_matters.each do |file_matter|
                tr
                  / td= file_matter.year
                  td= file_matter.file_code
                  td= file_matter.title
                  td= file_matter.case_number
                  td 
                    = link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_file_matter_path(file_matter), class: 'btn btn-xs btn-warning',"data-toggle"=> "tooltip", "data-placement" => "top", "title" => "Edit"
                    '&nbsp
                    = link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, file_matter_path(file_matter), method: :delete, 'data-confirm' => 'Are you sure you want to delete this file_matter?', class: 'btn btn-xs btn-danger'," data-toggle"=> "tooltip", "data-placement" => "top", "title" => "Delete"
          div.pull-right.apple_pagination.col-sm-12
            = will_paginate @users

app/views/file_matters/new.html.slim
.panel.panel-warning
  .panel-heading
    h3.panel-title Create Case Reference
  .panel-body
		.col-sm-12
			.row
				= render 'form'