config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'visitors#index'
  namespace :account do
    resources :users
  end
  resources :clients
  resources :file_matters do
  	get :autocomplete_client_name, :on => :collection
	end
  resources :lawyers
  resources :carl_entries
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
br
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'DASHBOARD', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
    <li>
      <%= link_to 'ENTRY FORM', carl_entries_path %>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">ADMIN SETUP<span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to 'USERS', account_users_path %>
        </li>
        <li>
          <%= link_to 'LAWYERS', lawyers_path %>

        </li>
        <!-- <li><a href="#">LAWYERS</a></li> -->
        <li>
          <%= link_to 'CLIENTS', clients_path %>
          
        </li>
        <!-- <li class="divider"></li> -->
        <li>
          <%= link_to 'CASE REFERENCES', file_matters_path %>

        </li>
        <!-- <li class="divider"></li> -->
        
      </ul>
    </li>
  </ul>
</div>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'PMFLS CA System'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Rails Bootstrap'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      .container-fluid
        .row
          == render 'layouts/messages'
          == yield